#!/bin/bash

curl -H 'Content-Type: application/json' -d '{"name": "firebolt"}' -X POST mcsim-cluster_api_1:5000/sim
curl -H 'Content-Type: application/json' -d '{"name": "frostbite"}' -X POST mcsim-cluster_api_1:5000/sim
curl -H 'Content-Type: application/json' -d '{"name": "radiantflash"}' -X POST mcsim-cluster_api_1:5000/sim
curl -H 'Content-Type: application/json' -d '{"name": "magneticSling"}' -X POST mcsim-cluster_api_1:5000/sim
curl -H 'Content-Type: application/json' -d '{"name": "crystal-hammer"}' -X POST mcsim-cluster_api_1:5000/sim